Repository dreamyPatisiel/devdevdev-server, pull requests merged in 2024-03, with the labels that each got.

#20 [DP-132] PickRepositoryImpl 쿼리 수정
  src/main/java/com/dreamypatisiel/devdevdev/DevdevdevApplication.java
  src/main/java/com/dreamypatisiel/devdevdev/LocalInitData.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/entity/Pick.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/entity/embedded/Count.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/policy/PickPopularScorePolicy.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/policy/PopularScorePolicy.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/pick/PickRepositoryCustom.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/pick/PickRepositoryImpl.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/pick/PickSort.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/GuestPickService.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/MemberPickService.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/response/PicksResponse.java
  src/main/java/com/dreamypatisiel/devdevdev/global/utils/BigDecimalUtils.java
  src/main/resources/static/docs/index.html
  src/test/java/com/dreamypatisiel/devdevdev/domain/entity/embedded/CountTest.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/policy/PickPopularScorePolicyTest.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/repository/pick/PickRepositoryTest.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/GuestPickServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/MemberPickServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/global/utils/BigDecimalUtilsTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/controller/PickControllerTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/PickControllerDocsTest.java
Labels: bug

#25 [DP-148] 토큰 예외 REST DOCS 추가
  src/docs/asciidoc/api/common/common.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/dreamypatisiel/devdevdev/global/security/filter/SecurityExceptionFilter.java
  src/main/java/com/dreamypatisiel/devdevdev/global/security/jwt/handler/JwtAuthenticationEntryPointHandler.java
  src/main/java/com/dreamypatisiel/devdevdev/web/controller/LogoutController.java
  src/main/java/com/dreamypatisiel/devdevdev/web/controller/exception/ApiControllerAdvice.java
  src/main/resources/static/docs/index.html
  src/test/java/com/dreamypatisiel/devdevdev/web/controller/LogoutControllerTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/controller/TokenControllerTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/JwtExceptionDocsTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/SupportControllerDocsTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/TokenControllerDocsTest.java
Labels: good first issue

#33 [DP-59] 기술블로그 검색 API
  .github/workflows/build.yml
  src/docs/asciidoc/api/tech-article/main.adoc
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/techArticle/TechArticleSort.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/response/TechArticleResponse.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/GuestTechArticleService.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/MemberTechArticleService.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/TechArticleService.java
  src/main/java/com/dreamypatisiel/devdevdev/elastic/domain/service/ElasticTechArticleService.java
  src/main/java/com/dreamypatisiel/devdevdev/web/controller/PickController.java
  src/main/java/com/dreamypatisiel/devdevdev/web/controller/TechArticleController.java
  src/main/resources/static/docs/index.html
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/pick/MemberPickServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/GuestTechArticleServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/MemberTechArticleServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/TechArticleServiceStrategyTest.java
  src/test/java/com/dreamypatisiel/devdevdev/elastic/domain/service/ElasticTechArticleServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/elastic/domain/service/ElasticsearchSupportTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/controller/TechArticleControllerTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/TechArticleControllerDocsTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/format/ApiDocsFormatGenerator.java
Labels: enhancement
