Repository dreamyPatisiel/devdevdev-server, pull requests merged in 2024-05, with the labels that each got.

#48 [DP-188] 기술블로그 메인/상세 응답 DTO 분리
  src/main/java/com/dreamypatisiel/devdevdev/domain/entity/TechArticle.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/entity/embedded/Count.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/response/TechArticleDetailResponse.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/response/TechArticleMainResponse.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/GuestTechArticleService.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/MemberTechArticleService.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/TechArticleCommonService.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/TechArticleService.java
  src/main/java/com/dreamypatisiel/devdevdev/web/controller/MypageController.java
  src/main/java/com/dreamypatisiel/devdevdev/web/controller/TechArticleController.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/GuestTechArticleServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/MemberTechArticleServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/controller/TechArticleControllerTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/TechArticleControllerDocsTest.java
Labels: fix

#52 [DP-93] 신규 가입시 닉네임 자동생성
  src/main/java/com/dreamypatisiel/devdevdev/LocalInitData.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/entity/Member.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/entity/MemberNicknameDictionary.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/entity/embedded/Word.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/entity/enums/WordType.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/member/MemberRepository.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/member/memberNicknameDictionary/MemberNicknameDictionaryRepository.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/member/memberNicknameDictionary/custom/MemberNicknameDictionaryRepositoryCustom.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/member/memberNicknameDictionary/custom/MemberNicknameDictionaryRepositoryImpl.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/member/MemberNicknameDictionaryService.java
  src/main/java/com/dreamypatisiel/devdevdev/global/common/MemberProvider.java
  src/main/java/com/dreamypatisiel/devdevdev/global/security/jwt/service/JwtMemberService.java
  src/main/java/com/dreamypatisiel/devdevdev/global/security/oauth2/model/SocialMemberDto.java
  src/main/java/com/dreamypatisiel/devdevdev/global/security/oauth2/service/OAuth2MemberService.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/repository/techArticle/TechArticleRepositoryTest.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/member/MemberNicknameDictionaryServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/pick/GuestPickServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/pick/MemberPickServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/MemberTechArticleServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/global/common/MemberProviderTest.java
  src/test/java/com/dreamypatisiel/devdevdev/global/security/jwt/service/JwtMemberServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/global/security/oauth2/handler/OAuth2SuccessHandlerTest.java
  src/test/java/com/dreamypatisiel/devdevdev/global/security/oauth2/service/AppOAuth2MemberServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/controller/LogoutControllerTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/controller/MyPageControllerTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/controller/PickControllerTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/controller/TechArticleControllerTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/controller/TokenControllerTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/JwtExceptionDocsTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/LogoutControllerDocsTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/MyPageControllerDocsTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/PickControllerDocsTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/TechArticleControllerDocsTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/TokenControllerDocsTest.java
Labels: fix

#53 [DP-177] 회원탈퇴 API
  src/docs/asciidoc/api/mypage/delete-member.adoc
  src/main/java/com/dreamypatisiel/devdevdev/domain/entity/Member.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/member/AnonymousMemberRepository.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/member/MemberService.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/GuestPickService.java
  src/main/java/com/dreamypatisiel/devdevdev/global/security/oauth2/handler/OAuth2SuccessHandler.java
  src/main/java/com/dreamypatisiel/devdevdev/web/controller/MypageController.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/member/MemberServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/pick/GuestPickServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/controller/MyPageControllerTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/MyPageControllerDocsTest.java
Labels: enhancement

#55 [DP-176] 내가 작성한 픽픽픽 API
  src/docs/asciidoc/api/common/common.adoc
  src/docs/asciidoc/api/member/logout.adoc
  src/docs/asciidoc/api/member/member.adoc
  src/docs/asciidoc/api/mypage/mypage.adoc
  src/docs/asciidoc/api/mypage/mypick-main.adoc
  src/docs/asciidoc/api/pick/pick.adoc
  src/docs/asciidoc/api/tech-article/tech-article.adoc
  src/docs/asciidoc/api/token/token-refresh/token-refresh.adoc
  src/docs/asciidoc/api/token/token-test/token-test-admin.adoc
  src/docs/asciidoc/api/token/token-test/token-test-user.adoc
  src/docs/asciidoc/api/token/token.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/dreamypatisiel/devdevdev/domain/entity/Member.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/entity/PickOption.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/entity/PickOptionImage.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/entity/enums/ContentStatus.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/pick/custom/PickRepositoryCustom.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/pick/custom/PickRepositoryImpl.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/member/MemberNicknameDictionaryService.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/member/MemberService.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/MemberPickService.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/response/MyPickMainOptionResponse.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/response/MyPickMainResponse.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/response/PickMainResponse.java
  src/main/java/com/dreamypatisiel/devdevdev/web/controller/MypageController.java
  src/main/java/com/dreamypatisiel/devdevdev/web/controller/PickController.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/repository/pick/PickRepositoryTest.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/member/MemberNicknameDictionaryServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/member/MemberServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/controller/MyPageControllerTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/MyPageControllerDocsTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/PickControllerDocsTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/format/ApiDocsFormatGenerator.java
Labels: enhancement

#56 [DP-193] 로그인시 회원 정보(이메일, 닉네임) 쿠키에 담아 응답
  src/main/java/com/dreamypatisiel/devdevdev/domain/entity/Member.java
  src/main/java/com/dreamypatisiel/devdevdev/global/security/jwt/model/JwtCookieConstant.java
  src/main/java/com/dreamypatisiel/devdevdev/global/security/oauth2/handler/OAuth2SuccessHandler.java
  src/main/java/com/dreamypatisiel/devdevdev/global/utils/CookieUtils.java
  src/test/java/com/dreamypatisiel/devdevdev/global/security/oauth2/handler/OAuth2SuccessHandlerTest.java
  src/test/java/com/dreamypatisiel/devdevdev/global/utils/CookieUtilsTest.java
Labels: fix

#59 [DP-210] 픽픽픽/기술블로그 페이지네이션 에러 수정 & 픽픽픽 옵션 내용 null 가능하도록 수정
  src/main/java/com/dreamypatisiel/devdevdev/domain/entity/PickOption.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/pick/custom/PickRepositoryImpl.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/techArticle/custom/TechArticleRepositoryImpl.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/response/PickDetailOptionResponse.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/entity/embedded/PickOptionContentsTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/controller/TechArticleControllerTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/TechArticleControllerDocsTest.java
Labels: bug

#57 [DP-205] 북마크, 회원탈퇴 내부 자잘한 수정
  src/docs/asciidoc/api/mypage/delete-member.adoc
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/techArticle/custom/TechArticleRepositoryCustom.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/techArticle/custom/TechArticleRepositoryImpl.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/member/MemberService.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/response/CompanyResponse.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/response/TechArticleDetailResponse.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/response/TechArticleMainResponse.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/response/util/TechArticleResponseUtils.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/GuestTechArticleService.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/MemberTechArticleService.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/TechArticleCommonService.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/TechArticleService.java
  src/main/java/com/dreamypatisiel/devdevdev/elastic/data/domain/ElasticSlice.java
  src/main/java/com/dreamypatisiel/devdevdev/elastic/domain/service/ElasticService.java
  src/main/java/com/dreamypatisiel/devdevdev/elastic/domain/service/ElasticTechArticleService.java
  src/main/java/com/dreamypatisiel/devdevdev/web/controller/MypageController.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/repository/techArticle/TechArticleRepositoryTest.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/member/MemberServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/GuestTechArticleServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/MemberTechArticleServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/elastic/domain/service/ElasticTechArticleServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/controller/MyPageControllerTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/controller/TechArticleControllerTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/MyPageControllerDocsTest.java
Labels: fix

#61 [DP-219] 검색 키워드에 특수문자가 있을 경우 예외 발생
  src/docs/asciidoc/api/tech-article/main.adoc
  src/main/java/com/dreamypatisiel/devdevdev/domain/exception/TechArticleExceptionMessage.java
  src/main/java/com/dreamypatisiel/devdevdev/elastic/domain/service/ElasticTechArticleService.java
  src/main/java/com/dreamypatisiel/devdevdev/web/controller/exception/ApiControllerAdvice.java
  src/test/java/com/dreamypatisiel/devdevdev/elastic/domain/service/ElasticTechArticleServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/controller/TechArticleControllerTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/TechArticleControllerDocsTest.java
Labels: fix
