Repository dreamyPatisiel/devdevdev-server, pull requests merged in 2024-10, with the labels that each got.

#108 [DP-252] 한글 초성 검색, 자/모음 분리 검색 가능하도록 수정 (cherry pick)
  src/main/java/com/dreamypatisiel/devdevdev/elastic/domain/document/ElasticKeyword.java
  src/main/java/com/dreamypatisiel/devdevdev/elastic/domain/service/ElasticKeywordService.java
  src/test/java/com/dreamypatisiel/devdevdev/elastic/domain/service/ElasticKeywordServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/controller/KeywordControllerTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/KeywordControllerDocsTest.java
Labels: feat

#107 [DP-373] 기술블로그 메인 조회시 썸네일 회사 로고 여부 isLogoImage 필드 추가
  src/main/java/com/dreamypatisiel/devdevdev/web/dto/response/techArticle/TechArticleMainResponse.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/MyPageControllerDocsTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/TechArticleControllerDocsTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/dto/response/techArticle/TechArticleMainResponseTest.java
Labels: fix

#105 [DP-374] 기술블로그 북마크 상태값 클라의존 제거
  src/main/java/com/dreamypatisiel/devdevdev/LocalInitData.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/entity/Bookmark.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/GuestTechArticleService.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/MemberTechArticleService.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/MemberTechCommentService.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/TechArticleService.java
  src/main/java/com/dreamypatisiel/devdevdev/web/controller/techArticle/TechArticleController.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/GuestTechArticleServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/MemberTechArticleServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/controller/techArticle/TechArticleControllerTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/TechArticleControllerDocsTest.java
Labels: fix

#109 [DP-393] 픽픽픽 댓글/답글 조회 API 필드 추가
  src/main/java/com/dreamypatisiel/devdevdev/domain/entity/PickComment.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/exception/GuestExceptionMessage.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/GuestPickCommentService.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/GuestPickService.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/MemberPickCommentService.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/MemberPickService.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/PickCommentService.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/PickCommonService.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/PickServiceStrategy.java
  src/main/java/com/dreamypatisiel/devdevdev/web/controller/pick/PickCommentController.java
  src/main/java/com/dreamypatisiel/devdevdev/web/dto/response/pick/PickCommentsResponse.java
  src/main/java/com/dreamypatisiel/devdevdev/web/dto/response/pick/PickRepliedCommentsResponse.java
  src/main/java/com/dreamypatisiel/devdevdev/web/dto/util/CommentResponseUtil.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/pick/GuestPickCommentServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/pick/GuestPickServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/pick/MemberPickCommentServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/controller/pick/PickCommentControllerTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/PickCommentControllerDocsTest.java
Labels: fix

#111 [DP-399] 픽픽픽 댓글/답글 조회 API 필드 추가(isRecommend, parentCommentMemberId, parentCommentAuthor)
  src/docs/asciidoc/api/pick-commnet/pick-best-comment-get.adoc
  src/docs/asciidoc/api/pick-commnet/pick-comment-reply-register.adoc
  src/docs/asciidoc/api/pick-commnet/pick-comment.adoc
  src/main/java/com/dreamypatisiel/devdevdev/domain/entity/PickComment.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/entity/PickCommentRecommend.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/policy/BestCommentPolicy.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/policy/PickBestCommentsPolicy.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/pick/PickCommentRecommendRepository.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/pick/PickCommentRepository.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/pick/custom/PickCommentRepositoryCustom.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/pick/custom/PickCommentRepositoryImpl.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/GuestPickCommentService.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/GuestPickService.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/MemberPickCommentService.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/MemberPickService.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/PickCommentService.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/PickCommonService.java
  src/main/java/com/dreamypatisiel/devdevdev/web/controller/common/BlameController.java
  src/main/java/com/dreamypatisiel/devdevdev/web/controller/pick/PickCommentController.java
  src/main/java/com/dreamypatisiel/devdevdev/web/dto/response/pick/PickCommentsResponse.java
  src/main/java/com/dreamypatisiel/devdevdev/web/dto/response/pick/PickRepliedCommentsResponse.java
  src/main/java/com/dreamypatisiel/devdevdev/web/dto/util/CommentResponseUtil.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/pick/GuestPickCommentServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/pick/MemberPickCommentServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/controller/pick/PickCommentControllerTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/PickCommentControllerDocsTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/format/ApiDocsFormatGenerator.java
Labels: fix

#117 [DP-406] 픽픽픽 메인/상세, 투표 중복 이슈 + 픽픽픽 댓글 추천 관련 응답 값 수정
  src/main/java/com/dreamypatisiel/devdevdev/domain/entity/AnonymousMember.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/entity/Member.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/MemberPickService.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/PickService.java
  src/main/java/com/dreamypatisiel/devdevdev/web/dto/response/pick/PickCommentRecommendResponse.java
  src/main/java/com/dreamypatisiel/devdevdev/web/dto/response/pick/PickCommentsResponse.java
  src/main/java/com/dreamypatisiel/devdevdev/web/dto/response/pick/PickRepliedCommentsResponse.java
  src/main/java/com/dreamypatisiel/devdevdev/web/dto/response/techArticle/TechCommentRecommendResponse.java
  src/main/java/com/dreamypatisiel/devdevdev/web/dto/response/techArticle/TechCommentsResponse.java
  src/main/java/com/dreamypatisiel/devdevdev/web/dto/response/techArticle/TechRepliedCommentsResponse.java
  src/main/java/com/dreamypatisiel/devdevdev/web/dto/util/CommentResponseUtil.java
  src/main/java/com/dreamypatisiel/devdevdev/web/dto/util/PickResponseUtils.java
  src/main/java/com/dreamypatisiel/devdevdev/web/dto/util/TechArticleResponseUtils.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/pick/GuestPickCommentServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/pick/MemberPickCommentServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/MemberTechCommentServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/global/security/oauth2/service/OAuth2UserServiceImplTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/controller/pick/PickCommentControllerTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/controller/techArticle/TechArticleCommentControllerTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/PickCommentControllerDocsTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/TechArticleCommentControllerDocsTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/dto/util/PickResponseUtilsTest.java
Labels: bug, fix

#119 [DP-409] 기술블로그 베스트 댓글/답글 API 개발
  src/docs/asciidoc/api/tech-article-comment/tech-article-best-comment-get.adoc
  src/docs/asciidoc/api/tech-article-comment/tech-article-comment.adoc
  src/main/java/com/dreamypatisiel/devdevdev/domain/entity/TechCommentRecommend.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/policy/TechBestCommentsPolicy.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/techArticle/TechCommentRepository.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/techArticle/TechCommentSort.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/techArticle/custom/TechCommentRepositoryCustom.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/techArticle/custom/TechCommentRepositoryImpl.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/PickCommonService.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/techArticle/MemberTechArticleService.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/techComment/GuestTechCommentService.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/techComment/MemberTechCommentService.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/techComment/TechCommentCommonService.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/techComment/TechCommentService.java
  src/main/java/com/dreamypatisiel/devdevdev/web/controller/pick/PickCommentController.java
  src/main/java/com/dreamypatisiel/devdevdev/web/controller/techArticle/TechArticleCommentController.java
  src/main/java/com/dreamypatisiel/devdevdev/web/dto/response/techArticle/TechRepliedCommentsResponse.java
  src/main/java/com/dreamypatisiel/devdevdev/web/dto/util/CommentResponseUtil.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/pick/PickCommonServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/GuestTechCommentServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/MemberTechCommentServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/controller/techArticle/TechArticleCommentControllerTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/TechArticleCommentControllerDocsTest.java
Labels: bug, fix, feat
