Repository dreamyPatisiel/devdevdev-server, pull requests merged in 2024-08, with the labels that each got.

#82 [DP-252] 한글 초성 검색, 자/모음 분리 검색 가능하도록 수정
  src/main/java/com/dreamypatisiel/devdevdev/elastic/domain/document/ElasticKeyword.java
  src/main/java/com/dreamypatisiel/devdevdev/elastic/domain/service/ElasticKeywordService.java
  src/test/java/com/dreamypatisiel/devdevdev/elastic/domain/service/ElasticKeywordServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/controller/KeywordControllerTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/KeywordControllerDocsTest.java
Labels: fix, feat

#85 [DP-335] 픽픽픽 댓글 작성 API
  src/docs/asciidoc/api/pick-commnet/pick-comment-register.adoc
  src/docs/asciidoc/api/pick-commnet/pick-comment.adoc
  src/docs/asciidoc/api/pick/pick-modify.adoc
  src/docs/asciidoc/api/pick/pick-register.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/dreamypatisiel/devdevdev/LocalInitData.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/entity/PickComment.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/entity/PickOption.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/entity/PickReply.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/entity/PickVote.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/entity/TechComment.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/entity/TechReply.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/entity/embedded/CommentContents.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/entity/embedded/Count.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/exception/PickExceptionMessage.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/pick/PickCommentRepository.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/pick/PickRepository.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/pick/PickVoteRepository.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/pick/custom/PickRepositoryImpl.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/GuestPickService.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/MemberPickCommentService.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/MemberPickService.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/PickCommonService.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/PickMultiServiceHandler.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/PickService.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/dto/VotePickOptionDto.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/response/PickCommentResponse.java
  src/main/java/com/dreamypatisiel/devdevdev/limiter/LimiterPlan.java
  src/main/java/com/dreamypatisiel/devdevdev/openai/embeddings/EmbeddingsService.java
  src/main/java/com/dreamypatisiel/devdevdev/web/controller/pick/PickCommentController.java
  src/main/java/com/dreamypatisiel/devdevdev/web/controller/pick/PickController.java
  src/main/java/com/dreamypatisiel/devdevdev/web/controller/pick/request/DeletePickOptionImageRequest.java
  src/main/java/com/dreamypatisiel/devdevdev/web/controller/pick/request/ModifyPickOptionRequest.java
  src/main/java/com/dreamypatisiel/devdevdev/web/controller/pick/request/ModifyPickRequest.java
  src/main/java/com/dreamypatisiel/devdevdev/web/controller/pick/request/RegisterPickCommentRequest.java
  src/main/java/com/dreamypatisiel/devdevdev/web/controller/pick/request/RegisterPickOptionRequest.java
  src/main/java/com/dreamypatisiel/devdevdev/web/controller/pick/request/RegisterPickRequest.java
  src/main/java/com/dreamypatisiel/devdevdev/web/controller/pick/request/VotePickOptionRequest.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/entity/embedded/CommentContentsTest.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/pick/GuestPickServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/pick/MemberPickCommentServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/pick/MemberPickServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/controller/pick/PickCommentControllerTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/controller/pick/PickControllerTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/PickCommentControllerDocsTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/PickControllerDocsTest.java
Labels: feat

#87 [DP-339] 픽픽픽 댓글 수정 API
  src/docs/asciidoc/api/pick-commnet/pick-comment-modify.adoc
  src/docs/asciidoc/api/pick-commnet/pick-comment-register.adoc
  src/docs/asciidoc/api/pick-commnet/pick-comment.adoc
  src/main/java/com/dreamypatisiel/devdevdev/domain/entity/PickComment.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/exception/PickExceptionMessage.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/pick/PickCommentRepository.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/pick/PickRepository.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/MemberPickCommentService.java
  src/main/java/com/dreamypatisiel/devdevdev/web/controller/pick/PickCommentController.java
  src/main/java/com/dreamypatisiel/devdevdev/web/controller/pick/request/ModifyPickCommentRequest.java
  src/main/java/com/dreamypatisiel/devdevdev/web/controller/pick/request/RegisterPickCommentRequest.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/pick/MemberPickCommentServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/controller/pick/PickCommentControllerTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/PickCommentControllerDocsTest.java
Labels: feat

#86 [DP-295] 기술블로그 댓글 작성
  src/docs/asciidoc/api/tech-article-comments/tech-article-comments-register.adoc
  src/docs/asciidoc/api/tech-article-comments/tech-article-comments.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/dreamypatisiel/devdevdev/domain/entity/PickComment.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/entity/TechComment.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/entity/embedded/CommentContents.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/techArticle/TechCommentRepository.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/response/TechCommentRegisterResponse.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/MemberTechCommentService.java
  src/main/java/com/dreamypatisiel/devdevdev/exception/CommentContentException.java
  src/main/java/com/dreamypatisiel/devdevdev/exception/CommentContentsException.java
  src/main/java/com/dreamypatisiel/devdevdev/web/controller/techArticle/KeywordController.java
  src/main/java/com/dreamypatisiel/devdevdev/web/controller/techArticle/TechArticleCommentController.java
  src/main/java/com/dreamypatisiel/devdevdev/web/controller/techArticle/TechArticleController.java
  src/main/java/com/dreamypatisiel/devdevdev/web/controller/techArticle/request/RegisterKeywordRequest.java
  src/main/java/com/dreamypatisiel/devdevdev/web/controller/techArticle/request/RegisterTechCommentRequest.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/entity/embedded/CommentContentsTest.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/repository/techArticle/TechArticleRepositoryTest.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/MemberTechCommentServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/TechArticleServiceStrategyTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/controller/techArticle/KeywordControllerTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/controller/techArticle/TechArticleCommentControllerTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/controller/techArticle/TechArticleControllerTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/TechArticleCommentControllerDocsTest.java
Labels: feat

#88 [PRD-340] 픽픽픽 댓글 삭제 API
  src/docs/asciidoc/api/pick-commnet/pick-comment-delete.adoc
  src/docs/asciidoc/api/pick-commnet/pick-comment-modify.adoc
  src/docs/asciidoc/api/pick-commnet/pick-comment-register.adoc
  src/docs/asciidoc/api/pick-commnet/pick-comment.adoc
  src/main/java/com/dreamypatisiel/devdevdev/domain/entity/PickComment.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/pick/PickCommentRepository.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/MemberPickCommentService.java
  src/main/java/com/dreamypatisiel/devdevdev/web/controller/pick/PickCommentController.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/pick/MemberPickCommentServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/controller/pick/PickCommentControllerTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/PickCommentControllerDocsTest.java
Labels: feat

#89 [DP-295] 기술블로그 댓글 수정 API
  src/docs/asciidoc/api/tech-article-comment/tech-article-comment-modify.adoc
  src/docs/asciidoc/api/tech-article-comment/tech-article-comment-register.adoc
  src/docs/asciidoc/api/tech-article-comment/tech-article-comment.adoc
  src/docs/asciidoc/api/tech-article-comments/tech-article-comments.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/dreamypatisiel/devdevdev/domain/entity/TechComment.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/exception/TechArticleExceptionMessage.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/techArticle/TechCommentRepository.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/response/TechCommentResponse.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/MemberTechCommentService.java
  src/main/java/com/dreamypatisiel/devdevdev/web/controller/techArticle/TechArticleCommentController.java
  src/main/java/com/dreamypatisiel/devdevdev/web/controller/techArticle/request/ModifyTechCommentRequest.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/MemberTechCommentServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/controller/techArticle/TechArticleCommentControllerTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/TechArticleCommentControllerDocsTest.java
Labels: feat

#90 [DP-295] 기술블로그 댓글 삭제 API
  src/docs/asciidoc/api/tech-article-comment/tech-article-comment-delete.adoc
  src/docs/asciidoc/api/tech-article-comment/tech-article-comment-modify.adoc
  src/docs/asciidoc/api/tech-article-comment/tech-article-comment.adoc
  src/main/java/com/dreamypatisiel/devdevdev/domain/entity/TechComment.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/techArticle/TechCommentRepository.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/MemberTechCommentService.java
  src/main/java/com/dreamypatisiel/devdevdev/web/controller/techArticle/TechArticleCommentController.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/MemberTechCommentServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/controller/techArticle/TechArticleCommentControllerTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/TechArticleCommentControllerDocsTest.java
Labels: feat

#92 [DP-347] 픽픽픽 답글 수정 API
  src/docs/asciidoc/api/pick-commnet/pick-comment.adoc
  src/docs/asciidoc/api/pick-commnet/pick-reply-modify.adoc
  src/main/java/com/dreamypatisiel/devdevdev/domain/entity/PickComment.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/entity/PickReply.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/exception/PickExceptionMessage.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/pick/PickReplyRepository.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/pick/custom/PickReplyRepositoryCustom.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/pick/custom/PickReplyRepositoryImpl.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/MemberPickCommentService.java
  src/main/java/com/dreamypatisiel/devdevdev/web/controller/pick/PickCommentController.java
  src/main/java/com/dreamypatisiel/devdevdev/web/controller/pick/request/ModifyPickReplyRequest.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/repository/pick/PickReplyRepositoryTest.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/pick/MemberPickCommentServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/controller/pick/PickCommentControllerTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/PickCommentControllerDocsTest.java
Labels: feat

#96 [DP-333] 엘라스틱서치 테스트코드 데이터 수리
  src/main/java/com/dreamypatisiel/devdevdev/elastic/domain/service/ElasticTechArticleService.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/GuestTechArticleServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/MemberTechArticleServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/MemberTechCommentServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/elastic/domain/service/ElasticTechArticleServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/elastic/domain/service/ElasticsearchSupportTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/controller/MyPageControllerTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/controller/techArticle/TechArticleControllerTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/MyPageControllerDocsTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/TechArticleControllerDocsTest.java
Labels: fix
