Repository dreamyPatisiel/devdevdev-server, pull requests merged in 2024-11, with the labels that each got.

#121 [DP-412] 픽픽픽 댓글/답글 조회 체크박스 정책 수정 대응
  src/docs/asciidoc/api/tech-article-comment/tech-article-comment-recommend.adoc
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/pick/custom/PickCommentRepositoryCustom.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/pick/custom/PickCommentRepositoryImpl.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/GuestPickCommentService.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/MemberPickCommentService.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/PickCommentService.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/PickCommonService.java
  src/main/java/com/dreamypatisiel/devdevdev/web/controller/pick/PickCommentController.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/pick/GuestPickCommentServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/pick/MemberPickCommentServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/TechArticleCommentControllerDocsTest.java
Labels: fix

#123 [DP-418] 픽픽픽 댓글/답글 총 갯수 계산식 변경
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/PickCommonService.java
Labels: bug, fix

#124 [DP-418] 픽픽픽 댓글/답글 총 갯수 계산식 변경
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/pick/custom/PickCommentRepositoryCustom.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/pick/custom/PickCommentRepositoryImpl.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/PickCommonService.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/pick/GuestPickCommentServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/controller/pick/PickCommentControllerTest.java
Labels: bug, fix

#125 [DP-418] 픽픽픽 댓글/답글 총 갯수 계산식 변경
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/pick/custom/PickCommentRepositoryImpl.java
Labels: bug, fix

#127 [DP-418] 픽픽픽 댓글/답글 총 갯수 계산식 변경
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/pick/PickCommentRepository.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/pick/custom/PickCommentRepositoryCustom.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/pick/custom/PickCommentRepositoryImpl.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/PickCommonService.java
  src/test/java/com/dreamypatisiel/devdevdev/web/controller/pick/PickCommentControllerTest.java
Labels: fix

#126 [DP-420] 기술블로그 베스트댓글 조회 정책 변경(추천수 1개 이상, 부모댓글개수 필드 추가)
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/techArticle/TechCommentRepository.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/techArticle/custom/TechCommentRepositoryImpl.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/techComment/GuestTechCommentService.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/techComment/MemberTechCommentService.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/techComment/TechCommentCommonService.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/techComment/TechCommentService.java
  src/main/java/com/dreamypatisiel/devdevdev/web/dto/SliceCommentCustom.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/GuestTechCommentServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/MemberTechCommentServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/controller/techArticle/TechArticleCommentControllerTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/TechArticleCommentControllerDocsTest.java
Labels: fix

#128 [DP-419] 픽픽픽 베스트 댓글 정책 수정 + 댓글/답글 조회 필드 추가
  src/docs/asciidoc/api/pick-commnet/pick-best-comment-get.adoc
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/pick/PickCommentRepository.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/pick/custom/PickCommentRepositoryImpl.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/MemberPickCommentService.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/PickCommonService.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/pick/GuestPickCommentServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/pick/MemberPickCommentServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/controller/pick/PickCommentControllerTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/PickCommentControllerDocsTest.java
Labels: fix

#129 [DP-420] fix(techComment): 삭제된 댓글은 부모 댓글 카운트 제외
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/techArticle/TechCommentRepository.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/techComment/TechCommentCommonService.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/GuestTechCommentServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/MemberTechCommentServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/TechArticleCommentControllerDocsTest.java
Labels: fix

#130 [DP-423] [댓글 기능] devdevdev server 운영서버 배포
  src/main/java/com/dreamypatisiel/devdevdev/domain/entity/TechArticle.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/entity/TechBlame.java
Labels: feat
