Repository dreamyPatisiel/devdevdev-server, pull requests merged in 2024-07, with the labels that each got.

#76 [DP-277] elasticsearch → opensearch 마이그레이션
  .github/workflows/build.yml
  .github/workflows/cicd-ec2-dev.yml
  .github/workflows/cicd-ec2-prod.yml
  .gitignore
  Dockerfile
  build.gradle
  src/main/java/com/dreamypatisiel/devdevdev/DevdevdevApplication.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/techArticle/TechArticleSort.java
  src/main/java/com/dreamypatisiel/devdevdev/elastic/config/ElasticsearchConfig.java
  src/main/java/com/dreamypatisiel/devdevdev/elastic/config/ElasticsearchIndexConfigService.java
  src/main/java/com/dreamypatisiel/devdevdev/elastic/config/OpenSearchRestClientConfiguration.java
  src/main/java/com/dreamypatisiel/devdevdev/elastic/domain/service/ElasticKeywordService.java
  src/main/java/com/dreamypatisiel/devdevdev/elastic/domain/service/ElasticTechArticleService.java
  src/main/java/com/dreamypatisiel/devdevdev/global/config/EmbeddedRedisServerConfig.java
  src/main/java/com/dreamypatisiel/devdevdev/global/security/jwt/filter/DevJwtAuthenticationFilter.java
  src/main/java/com/dreamypatisiel/devdevdev/global/security/jwt/filter/ProdJwtAuthenticationFilter.java
  src/main/resources/application-local.yml
  src/main/resources/application.yml
  src/main/resources/redis/redis-server-mac-x86
  src/test/java/com/dreamypatisiel/devdevdev/DevdevdevApplicationTests.java
  src/test/java/com/dreamypatisiel/devdevdev/elastic/config/ElasticsearchTestConfig.java
  src/test/java/com/dreamypatisiel/devdevdev/global/security/jwt/service/TokenServiceTest.java
  src/test/resources/application-test.yml
  src/test/resources/application.yml
Labels: fix

#77 [DP-277] elasticsearch → opensearch 마이그레이션
  .github/workflows/build.yml
  .github/workflows/cicd-ec2-dev.yml
  .github/workflows/cicd-ec2-prod.yml
  .gitignore
  build.gradle
  src/main/java/com/dreamypatisiel/devdevdev/DevdevdevApplication.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/techArticle/TechArticleSort.java
  src/main/java/com/dreamypatisiel/devdevdev/elastic/config/ElasticsearchConfig.java
  src/main/java/com/dreamypatisiel/devdevdev/elastic/config/ElasticsearchIndexConfigService.java
  src/main/java/com/dreamypatisiel/devdevdev/elastic/config/OpenSearchRestClientConfiguration.java
  src/main/java/com/dreamypatisiel/devdevdev/elastic/domain/service/ElasticKeywordService.java
  src/main/java/com/dreamypatisiel/devdevdev/elastic/domain/service/ElasticTechArticleService.java
  src/main/java/com/dreamypatisiel/devdevdev/global/config/EmbeddedRedisServerConfig.java
  src/main/resources/application-local.yml
  src/main/resources/application.yml
  src/main/resources/redis/redis-server-mac-x86
  src/test/java/com/dreamypatisiel/devdevdev/DevdevdevApplicationTests.java
  src/test/java/com/dreamypatisiel/devdevdev/elastic/config/ElasticsearchTestConfig.java
  src/test/resources/application-test.yml
  src/test/resources/application.yml
Labels: fix, feat

#78 [DP-315] 기술블로그 검색 쿼리스트링 기본연산자 AND 적용
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/techArticle/TechArticleSort.java
  src/main/java/com/dreamypatisiel/devdevdev/elastic/config/ElasticsearchConfig.java
  src/main/java/com/dreamypatisiel/devdevdev/elastic/constant/ElasticsearchConstant.java
  src/main/java/com/dreamypatisiel/devdevdev/elastic/domain/service/ElasticTechArticleService.java
  src/main/java/com/dreamypatisiel/devdevdev/global/security/jwt/filter/ProdJwtAuthenticationFilter.java
  src/main/resources/application-local.yml
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/GuestTechArticleServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/MemberTechArticleServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/elastic/domain/service/ElasticTechArticleServiceTest.java
  src/test/resources/application-test.yml
Labels: fix

#79 [DP-315] 기술블로그 검색 쿼리스트링 기본연산자 AND 적용
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/techArticle/TechArticleSort.java
  src/main/java/com/dreamypatisiel/devdevdev/elastic/config/ElasticsearchConfig.java
  src/main/java/com/dreamypatisiel/devdevdev/elastic/constant/ElasticsearchConstant.java
  src/main/java/com/dreamypatisiel/devdevdev/elastic/domain/service/ElasticTechArticleService.java
  src/main/java/com/dreamypatisiel/devdevdev/global/security/jwt/filter/ProdJwtAuthenticationFilter.java
  src/main/resources/application-local.yml
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/GuestTechArticleServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/MemberTechArticleServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/elastic/domain/service/ElasticTechArticleServiceTest.java
  src/test/resources/application-test.yml
Labels: fix

#80 [DP-328] 픽픽픽 투표 응답 버그 수정
  src/main/java/com/dreamypatisiel/devdevdev/domain/entity/AnonymousMember.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/entity/Member.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/entity/Pick.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/response/util/PickResponseUtils.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/response/util/TechArticleResponseUtils.java
Labels: bug, fix

#81 [DP-328] 픽픽픽 투표 응답 버그 수정
  src/main/java/com/dreamypatisiel/devdevdev/domain/entity/AnonymousMember.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/entity/Member.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/entity/Pick.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/response/util/PickResponseUtils.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/response/util/TechArticleResponseUtils.java
Labels: bug, fix
