Repository dreamyPatisiel/devdevdev-server, pull requests merged in 2025-01, with the labels that each got.

#134 [DP-452] fix: 일반회원 픽픽픽 작성시 자동 승인
  src/main/java/com/dreamypatisiel/devdevdev/domain/entity/Pick.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/pick/MemberPickServiceTest.java
Labels: fix

#133 [DP-447] 기술블로그 추천 API
  src/docs/asciidoc/api/tech-article/recommend.adoc
  src/docs/asciidoc/api/tech-article/tech-article.adoc
  src/main/java/com/dreamypatisiel/devdevdev/LocalInitData.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/entity/TechArticle.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/entity/TechArticleRecommend.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/techArticle/BookmarkRepository.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/techArticle/TechArticleRecommendRepository.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/member/AnonymousMemberService.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/GuestPickService.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/techArticle/GuestTechArticleService.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/techArticle/MemberTechArticleService.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/techArticle/TechArticleService.java
  src/main/java/com/dreamypatisiel/devdevdev/web/controller/techArticle/TechArticleController.java
  src/main/java/com/dreamypatisiel/devdevdev/web/dto/response/techArticle/TechArticleDetailResponse.java
  src/main/java/com/dreamypatisiel/devdevdev/web/dto/response/techArticle/TechArticleRecommendResponse.java
  src/main/java/com/dreamypatisiel/devdevdev/web/dto/util/TechArticleResponseUtils.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/repository/techArticle/TechArticleRepositoryTest.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/member/MemberServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/GuestTechArticleServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/MemberTechArticleServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/controller/MyPageControllerTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/controller/techArticle/TechArticleControllerTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/MyPageControllerDocsTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/PickControllerDocsTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/TechArticleControllerDocsTest.java
Labels: fix, feat

#136 [DP-447] fix: GA 값 없을 경우 대응
  src/main/java/com/dreamypatisiel/devdevdev/web/dto/util/TechArticleResponseUtils.java
Labels: fix

#137 [DP-449] 내가 썼어요 댓글 API 개발
  .github/workflows/build.yml
  build.gradle
  src/docs/asciidoc/api/mypage/comment-get.adoc
  src/docs/asciidoc/api/mypage/mypage.adoc
  src/main/java/com/dreamypatisiel/devdevdev/domain/entity/Pick.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/entity/TechArticle.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/comment/CommentRepository.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/comment/MyWrittenCommentDto.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/comment/mybatis/CommentMapper.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/pick/PickCommentRepository.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/pick/custom/PickCommentRepositoryCustom.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/pick/custom/PickCommentRepositoryImpl.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/techArticle/TechCommentRepository.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/techArticle/custom/TechCommentRepositoryCustom.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/techArticle/custom/TechCommentRepositoryImpl.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/member/MemberService.java
  src/main/java/com/dreamypatisiel/devdevdev/global/security/jwt/model/TokenExpireTime.java
  src/main/java/com/dreamypatisiel/devdevdev/web/controller/member/MypageController.java
  src/main/java/com/dreamypatisiel/devdevdev/web/dto/request/comment/MyWrittenCommentFilter.java
  src/main/java/com/dreamypatisiel/devdevdev/web/dto/request/comment/MyWrittenCommentRequest.java
  src/main/java/com/dreamypatisiel/devdevdev/web/dto/response/comment/MyWrittenCommentResponse.java
  src/main/java/com/dreamypatisiel/devdevdev/web/dto/response/member/MemberExitSurveyAnswerResponse.java
  src/main/java/com/dreamypatisiel/devdevdev/web/dto/util/CommentResponseUtil.java
  src/main/resources/application-local.yml
  src/main/resources/mapper/commment/Comment.xml
  src/test/java/com/dreamypatisiel/devdevdev/domain/repository/comment/CommentRepositoryTest.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/repository/comment/mybatis/CommentMapperTest.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/repository/pick/PickRepositoryTest.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/blame/MemberPickBlameServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/common/MemberBlameServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/member/MemberServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/pick/GuestPickServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/pick/MemberPickServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/GuestTechArticleServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/GuestTechCommentServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/MemberTechArticleServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/MemberTechCommentServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/controller/BlameControllerTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/controller/MyPageControllerTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/controller/MyPageControllerUsedMockServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/controller/pick/PickControllerTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/controller/techArticle/TechArticleCommentControllerTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/controller/techArticle/TechArticleControllerTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/BlameControllerDocsTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/MyPageControllerDocsUsedMockServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/TechArticleCommentControllerDocsTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/TechArticleControllerDocsTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/format/ApiDocsFormatGenerator.java
  src/test/java/com/dreamypatisiel/devdevdev/web/dto/response/techArticle/TechArticleMainResponseTest.java
  src/test/resources/application-test.yml
Labels: feat

#138 [DP-464] bugfix: 회원/익명회원의 추천 여부 조회 메서드 -> 해당 추천의 추천자가 회원/익명회원인지 필터링하는 로직 추가
  src/main/java/com/dreamypatisiel/devdevdev/domain/entity/TechArticleRecommend.java
  src/main/java/com/dreamypatisiel/devdevdev/web/dto/util/TechArticleResponseUtils.java
Labels: bug, fix

#139 fix: 기술블로그 추천 API 응답에 총 추천수 추가
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/techArticle/GuestTechArticleService.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/techArticle/MemberTechArticleService.java
  src/main/java/com/dreamypatisiel/devdevdev/web/dto/response/techArticle/TechArticleRecommendResponse.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/GuestTechArticleServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/MemberTechArticleServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/controller/techArticle/TechArticleControllerTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/TechArticleControllerDocsTest.java
Labels: fix

#135 [DP-455] fix: 토큰 만료기간 환경변수화
  src/main/java/com/dreamypatisiel/devdevdev/global/security/jwt/model/TokenExpireTime.java
  src/main/resources/application-jwt-local.yml
  src/test/resources/application-jwt-test.yml
Labels: fix
