Repository dreamyPatisiel/devdevdev-server, pull requests merged in 2025-07, with the labels that each got.

#162 [DP-536] 랜덤 닉네임 생성 API
  src/docs/asciidoc/api/mypage/mypage.adoc
  src/docs/asciidoc/api/mypage/random-nickname.adoc
  src/main/java/com/dreamypatisiel/devdevdev/LocalInitData.java
  src/main/java/com/dreamypatisiel/devdevdev/web/controller/member/MypageController.java
  src/test/java/com/dreamypatisiel/devdevdev/web/controller/member/LogoutControllerTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/controller/member/MyPageControllerTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/controller/member/MyPageControllerUsedMockServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/controller/member/TokenControllerTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/MyPageControllerDocsUsedMockServiceTest.java
Labels: documentation, feat

#164 [DP-535] 닉네임 변경 API
  src/docs/asciidoc/api/mypage/change-nickname.adoc
  src/main/java/com/dreamypatisiel/devdevdev/domain/entity/Member.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/exception/NicknameExceptionMessage.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/member/MemberService.java
  src/main/java/com/dreamypatisiel/devdevdev/web/controller/exception/ApiControllerAdvice.java
  src/main/java/com/dreamypatisiel/devdevdev/web/controller/member/MypageController.java
  src/main/java/com/dreamypatisiel/devdevdev/web/dto/request/member/ChangeNicknameRequest.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/entity/MemberTest.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/member/MemberServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/controller/member/MyPageControllerUsedMockServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/MyPageControllerDocsUsedMockServiceTest.java
Labels: documentation, feat

#167 [DP-538] 닉네임 변경 가능 여부 API
  src/docs/asciidoc/api/mypage/can-change-nickname.adoc
  src/docs/asciidoc/api/mypage/mypage.adoc
  src/main/java/com/dreamypatisiel/devdevdev/domain/entity/Member.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/member/MemberService.java
  src/main/java/com/dreamypatisiel/devdevdev/web/controller/member/MypageController.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/entity/MemberTest.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/member/MemberServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/controller/member/MyPageControllerUsedMockServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/MyPageControllerDocsUsedMockServiceTest.java
Labels: documentation, feat

#165 [DP-525] 익명회원 픽픽픽 답글 작성
  src/docs/asciidoc/api/pick-commnet/pick-comment-reply-register.adoc
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/GuestPickCommentService.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/GuestPickCommentServiceV2.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/GuestPickService.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/MemberPickCommentService.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/MemberPickService.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/PickCommentService.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/PickCommonService.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/dto/PickCommentDto.java
  src/main/java/com/dreamypatisiel/devdevdev/web/controller/pick/PickCommentController.java
  src/main/java/com/dreamypatisiel/devdevdev/web/controller/pick/PickController.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/pick/GuestPickCommentServiceV2Test.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/pick/MemberPickCommentServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/pick/PickTestUtils.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/PickCommentControllerDocsTest.java
Labels: documentation, fix, feat

#166 [DP-526] 익명회원 픽픽픽 댓글/답글 수정
  src/docs/asciidoc/api/pick-commnet/pick-comment-modify.adoc
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/pick/PickCommentRepository.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/GuestPickCommentService.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/GuestPickCommentServiceV2.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/GuestPickService.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/MemberPickCommentService.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/MemberPickService.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/PickCommentService.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/PickCommonService.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/dto/PickCommentDto.java
  src/main/java/com/dreamypatisiel/devdevdev/web/controller/pick/PickCommentController.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/pick/GuestPickCommentServiceV2Test.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/pick/MemberPickCommentServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/pick/PickTestUtils.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/PickCommentControllerDocsTest.java
Labels: documentation, fix, feat

#169 [DP-527] 익명회원 픽픽픽 댓글/답글 삭제
  src/docs/asciidoc/api/pick-commnet/pick-comment-delete.adoc
  src/docs/asciidoc/api/pick-commnet/pick-comment-modify.adoc
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/GuestPickCommentService.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/GuestPickCommentServiceV2.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/MemberPickCommentService.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/PickCommentService.java
  src/main/java/com/dreamypatisiel/devdevdev/web/controller/pick/PickCommentController.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/pick/GuestPickCommentServiceV2Test.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/pick/MemberPickCommentServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/PickCommentControllerDocsTest.java
Labels: documentation, fix, feat

#170 [DP-535] 닉네임 변경 API 응답 변경(변경된 닉네임 문자열 추가)
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/member/MemberService.java
  src/main/java/com/dreamypatisiel/devdevdev/web/controller/member/MypageController.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/member/MemberServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/controller/member/MyPageControllerUsedMockServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/MyPageControllerDocsUsedMockServiceTest.java
Labels: fix

#171 [DP-543] 픽픽픽 댓글/답글 조회 API 수정
  src/main/java/com/dreamypatisiel/devdevdev/domain/entity/AnonymousMember.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/entity/Member.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/entity/PickComment.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/pick/PickCommentRepository.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/pick/custom/PickCommentRepositoryImpl.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/member/AnonymousMemberService.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/GuestPickCommentService.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/GuestPickCommentServiceV2.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/MemberPickCommentService.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/PickCommentService.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/PickCommonService.java
  src/main/java/com/dreamypatisiel/devdevdev/web/controller/pick/PickCommentController.java
  src/main/java/com/dreamypatisiel/devdevdev/web/dto/response/pick/PickCommentsResponse.java
  src/main/java/com/dreamypatisiel/devdevdev/web/dto/response/pick/PickRepliedCommentsResponse.java
  src/main/java/com/dreamypatisiel/devdevdev/web/dto/util/CommentResponseUtil.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/pick/GuestPickCommentServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/pick/GuestPickCommentServiceV2Test.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/pick/MemberPickCommentServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/pick/PickTestUtils.java
  src/test/java/com/dreamypatisiel/devdevdev/web/controller/pick/PickCommentControllerTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/PickCommentControllerDocsTest.java
Labels: documentation, fix, feat

#174 fix(nickname): 회원 닉네임 변경 가능 시간 환경변수화
  src/main/java/com/dreamypatisiel/devdevdev/domain/entity/Member.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/policy/NicknameChangePolicy.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/member/MemberService.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/entity/MemberTest.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/member/MemberServiceTest.java
Labels: fix

#176 [DP-528] 익명회원 기술블로그 댓글 작성
  src/docs/asciidoc/api/tech-article-comment/tech-article-comment-register.adoc
  src/main/java/com/dreamypatisiel/devdevdev/domain/entity/TechComment.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/TechArticleServiceStrategy.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/dto/TechCommentDto.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/techComment/GuestTechCommentService.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/techComment/GuestTechCommentServiceV2.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/techComment/MemberTechCommentService.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/techComment/TechCommentCommonService.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/techComment/TechCommentService.java
  src/main/java/com/dreamypatisiel/devdevdev/web/controller/techArticle/TechArticleCommentController.java
  src/main/resources/application-local.yml
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/GuestTechCommentServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/MemberTechCommentServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/techComment/GuestTechCommentServiceV2Test.java
  src/test/java/com/dreamypatisiel/devdevdev/web/controller/techArticle/TechArticleCommentControllerTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/TechArticleCommentControllerDocsTest.java
Labels: documentation, fix, feat
