Repository dreamyPatisiel/devdevdev-server, pull requests merged in 2025-08, with the labels that each got.

#183 [DP-555] MySQL 마이그레이션 from MariaDB
  build.gradle
Labels: fix

#184 [DP-554] 검색어 자동완성 API (ES → MySQL 마이그레이션)
  src/main/java/com/dreamypatisiel/devdevdev/domain/entity/TechKeyword.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/techArticle/TechKeywordRepository.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/techArticle/custom/TechKeywordRepositoryCustom.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/techArticle/custom/TechKeywordRepositoryImpl.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/keyword/TechKeywordService.java
  src/main/java/com/dreamypatisiel/devdevdev/global/config/CustomMySQLFunctionContributor.java
  src/main/java/com/dreamypatisiel/devdevdev/global/utils/HangulUtils.java
  src/main/java/com/dreamypatisiel/devdevdev/web/controller/techArticle/KeywordController.java
  src/main/resources/META-INF/services/org.hibernate.boot.model.FunctionContributor
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/TechKeywordServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/elastic/domain/service/ElasticKeywordServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/global/utils/HangulUtilsTest.java
  src/test/java/com/dreamypatisiel/devdevdev/test/MySQLTestContainer.java
  src/test/java/com/dreamypatisiel/devdevdev/web/controller/techArticle/KeywordControllerTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/KeywordControllerDocsTest.java
Labels: documentation, fix

#188 main PR
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/pick/PickRepository.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/member/MemberService.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/MyPageControllerDocsTest.java
Labels: bug, fix

#189 [DP-558] 인스턴스 마이그레이션 from EC2
  .github/workflows/cicd-ec2-prod.yml
  .github/workflows/cicd-light-sail-prod.yml
  Dockerfile-prod
  src/main/java/com/dreamypatisiel/devdevdev/global/constant/SecurityConstant.java
  src/main/resources/application-local.yml
Labels: fix

#190 [DP-516] 기술블로그 검색어 조회시 score 누락 이슈 수정
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/techArticle/TechArticleDto.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/techArticle/custom/TechArticleRepositoryCustom.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/techArticle/custom/TechArticleRepositoryImpl.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/techArticle/GuestTechArticleService.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/techArticle/MemberTechArticleService.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/techArticle/TechArticleService.java
  src/main/java/com/dreamypatisiel/devdevdev/web/controller/techArticle/TechArticleController.java
  src/main/java/com/dreamypatisiel/devdevdev/web/dto/response/techArticle/TechArticleMainResponse.java
  src/test/java/com/dreamypatisiel/devdevdev/web/controller/notification/NotificationControllerTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/controller/techArticle/TechArticleControllerTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/NotificationControllerDocsTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/TechArticleControllerDocsTest.java
Labels: fix
