Repository dreamyPatisiel/devdevdev-server, pull requests merged in 2025-04, with the labels that each got.

#152 [DP-504] 알림 단건 읽기 API
  build.gradle
  src/docs/asciidoc/api/notification/notification.adoc
  src/docs/asciidoc/api/notification/read-notification.adoc
  src/main/java/com/dreamypatisiel/devdevdev/domain/entity/Notification.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/exception/NotificationExceptionMessage.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/notification/NotificationRepository.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/notification/NotificationService.java
  src/main/java/com/dreamypatisiel/devdevdev/web/controller/notification/NotificationController.java
  src/main/java/com/dreamypatisiel/devdevdev/web/dto/response/notification/NotificationReadResponse.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/notification/NotificationServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/controller/notification/NotificationControllerTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/controller/techArticle/TechArticleControllerTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/MyPageControllerDocsTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/NotificationControllerDocsTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/TechArticleControllerDocsTest.java
Labels: documentation, feat

#154 [DP-499] 알림 생성, 알림 전송 개발
  .gitignore
  src/docs/asciidoc/api/notification/notification.adoc
  src/docs/asciidoc/api/notification/notifications.adoc
  src/docs/asciidoc/api/notification/publish-notifications.adoc
  src/main/java/com/dreamypatisiel/devdevdev/domain/entity/ApiKey.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/entity/Company.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/entity/Member.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/entity/Notification.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/entity/TechArticle.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/entity/enums/NotificationType.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/ApiKeyRepository.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/SseEmitterRepository.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/notification/NotificationRepository.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/notification/custom/NotificationRepositoryCustom.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/notification/custom/NotificationRepositoryImpl.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/techArticle/SubscriptionRepository.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/ApiKeyService.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/notification/NotificationService.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/GuestPickService.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/pick/PickFacadeService.java
  src/main/java/com/dreamypatisiel/devdevdev/global/constant/SecurityConstant.java
  src/main/java/com/dreamypatisiel/devdevdev/global/security/jwt/filter/DevJwtAuthenticationFilter.java
  src/main/java/com/dreamypatisiel/devdevdev/global/security/jwt/filter/ProdJwtAuthenticationFilter.java
  src/main/java/com/dreamypatisiel/devdevdev/global/validator/EnumValidator.java
  src/main/java/com/dreamypatisiel/devdevdev/redis/config/EmbeddedRedisConfig.java
  src/main/java/com/dreamypatisiel/devdevdev/redis/config/EmbeddedRedisServerConfig.java
  src/main/java/com/dreamypatisiel/devdevdev/redis/config/RedisConfig.java
  src/main/java/com/dreamypatisiel/devdevdev/redis/config/RedisSubscribeConfig.java
  src/main/java/com/dreamypatisiel/devdevdev/redis/pub/NotificationPublisher.java
  src/main/java/com/dreamypatisiel/devdevdev/redis/pub/RedisNotificationPublisher.java
  src/main/java/com/dreamypatisiel/devdevdev/redis/sub/NotificationMessageDto.java
  src/main/java/com/dreamypatisiel/devdevdev/redis/sub/RedisNotificationSubscriber.java
  src/main/java/com/dreamypatisiel/devdevdev/test/TestController.java
  src/main/java/com/dreamypatisiel/devdevdev/web/controller/notification/NotificationController.java
  src/main/java/com/dreamypatisiel/devdevdev/web/controller/pick/PickController.java
  src/main/java/com/dreamypatisiel/devdevdev/web/controller/subscription/SubscriptionController.java
  src/main/java/com/dreamypatisiel/devdevdev/web/dto/request/publish/PublishTechArticle.java
  src/main/java/com/dreamypatisiel/devdevdev/web/dto/request/publish/PublishTechArticleRequest.java
  src/main/java/com/dreamypatisiel/devdevdev/web/dto/request/publish/RedisPublishRequest.java
  src/main/java/com/dreamypatisiel/devdevdev/web/dto/response/notification/NotificationReadResponse.java
  src/main/resources/mapper/comment/Comment.xml
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/ApiKeyServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/notification/MockNotificationServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/notification/NotificationServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/controller/MockMvcCharacterEncodingCustomizer.java
  src/test/java/com/dreamypatisiel/devdevdev/web/controller/MyPageControllerTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/controller/notification/NotificationControllerTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/controller/techArticle/TechArticleControllerTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/NotificationControllerDocsTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/SupportControllerDocsTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/TechArticleControllerDocsTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/TokenControllerDocsTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/custom/CustomPreprocessors.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/format/ApiDocsFormatGenerator.java
Labels: documentation, fix, feat

#155 [DP-502,503] 알림 팝업, 알림 페이지 조회 API
  src/docs/asciidoc/api/notification/get-notification-popup.adoc
  src/docs/asciidoc/api/notification/get-notifications.adoc
  src/docs/asciidoc/api/notification/notification.adoc
  src/main/java/com/dreamypatisiel/devdevdev/LocalInitData.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/entity/Bookmark.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/entity/TechArticleRecommend.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/entity/enums/NotificationType.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/exception/NotificationExceptionMessage.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/notification/custom/NotificationRepositoryCustom.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/notification/custom/NotificationRepositoryImpl.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/notification/NotificationService.java
  src/main/java/com/dreamypatisiel/devdevdev/web/controller/notification/NotificationController.java
  src/main/java/com/dreamypatisiel/devdevdev/web/dto/response/notification/NotificationNewArticleResponse.java
  src/main/java/com/dreamypatisiel/devdevdev/web/dto/response/notification/NotificationPopupNewArticleResponse.java
  src/main/java/com/dreamypatisiel/devdevdev/web/dto/response/notification/NotificationPopupResponse.java
  src/main/java/com/dreamypatisiel/devdevdev/web/dto/response/notification/NotificationResponse.java
  src/main/java/com/dreamypatisiel/devdevdev/web/dto/response/techArticle/CompanyResponse.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/notification/NotificationServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/controller/notification/NotificationControllerTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/NotificationControllerDocsTest.java
Labels: documentation, feat

#156 [DP-502] 알림 전체 개수 조회 API & 알림 생성일시 LocalDate → LocalDateTime 변경
  src/docs/asciidoc/api/notification/get-notification-unread-count.adoc
  src/docs/asciidoc/api/notification/notification.adoc
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/notification/custom/NotificationRepositoryCustom.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/notification/custom/NotificationRepositoryImpl.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/notification/NotificationService.java
  src/main/java/com/dreamypatisiel/devdevdev/web/controller/notification/NotificationController.java
  src/main/java/com/dreamypatisiel/devdevdev/web/dto/response/notification/NotificationNewArticleResponse.java
  src/main/java/com/dreamypatisiel/devdevdev/web/dto/response/notification/NotificationPopupNewArticleResponse.java
  src/main/java/com/dreamypatisiel/devdevdev/web/dto/response/notification/NotificationPopupResponse.java
  src/main/java/com/dreamypatisiel/devdevdev/web/dto/response/notification/NotificationResponse.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/notification/NotificationServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/controller/notification/NotificationControllerTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/NotificationControllerDocsTest.java
Labels: documentation, fix, feat

#157 [DP-515] sse heartbeat 스케줄러 개발
  src/docs/asciidoc/api/notification/notifications.adoc
  src/main/java/com/dreamypatisiel/devdevdev/DevdevdevApplication.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/SseEmitterRepository.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/notification/NotificationService.java
  src/main/java/com/dreamypatisiel/devdevdev/global/config/AsyncConfig.java
  src/main/java/com/dreamypatisiel/devdevdev/scheduler/AsyncHeartbeatSender.java
  src/main/java/com/dreamypatisiel/devdevdev/scheduler/SseEmitterHeartbeatScheduler.java
  src/test/java/com/dreamypatisiel/devdevdev/scheduler/AsyncHeartbeatSenderTest.java
  src/test/java/com/dreamypatisiel/devdevdev/scheduler/SseEmitterHeartbeatSchedulerTest.java
Labels: fix
