Repository dreamyPatisiel/devdevdev-server, pull requests merged in 2025-05, with the labels that each got.

#158 feat(notification): 알림 일괄 삭제 API
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/notification/NotificationRepository.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/notification/NotificationService.java
  src/main/java/com/dreamypatisiel/devdevdev/test/TestController.java
  src/main/java/com/dreamypatisiel/devdevdev/web/controller/notification/NotificationController.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/notification/NotificationServiceTest.java
Labels: feat

#159 [DP-518] SSE 하트비트 간헐적으로 안오는 이슈
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/SseEmitterRepository.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/notification/NotificationService.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/notification/MockNotificationServiceTest.java
Labels: bug, fix

#160 [DP-520] fix: 구독 가능한 기업 목록 - 기업명 추가
  src/main/java/com/dreamypatisiel/devdevdev/web/dto/response/subscription/SubscriableCompanyResponse.java
  src/test/java/com/dreamypatisiel/devdevdev/web/controller/subscription/SubscriptionControllerTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/SubscriptionControllerDocsTest.java
Labels: fix
