Repository dreamyPatisiel/devdevdev-server, pull requests merged in 2025-03, with the labels that each got.

#141 [DP-492] 구독/구독 취소 API 개발
  deploy-dev.sh
  src/docs/asciidoc/api/subscription/subscribe.adoc
  src/docs/asciidoc/api/subscription/unsubscribe.adoc
  src/main/java/com/dreamypatisiel/devdevdev/domain/entity/Company.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/entity/Subscription.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/exception/CompanyExceptionMessage.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/exception/SubscriptionExceptionMessage.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/techArticle/SubscriptionRepository.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/techArticle/custom/SubscriptionRepositoryCustom.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/techArticle/custom/SubscriptionRepositoryImpl.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/subscription/SubscriptionService.java
  src/main/java/com/dreamypatisiel/devdevdev/exception/SubscriptionException.java
  src/main/java/com/dreamypatisiel/devdevdev/global/properties/CorsProperties.java
  src/main/java/com/dreamypatisiel/devdevdev/web/controller/subscription/SubscriptionController.java
  src/main/java/com/dreamypatisiel/devdevdev/web/dto/request/subscription/SubscribeCompanyRequest.java
  src/main/java/com/dreamypatisiel/devdevdev/web/dto/response/techArticle/SubscriptionResponse.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/subscription/SubscriptionServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/controller/subscription/SubscriptionControllerTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/SubscriptionControllerDocsTest.java
Labels: documentation, feat

#142 [DP-493] 구독 가능한 기업 목록 조회 API
  src/docs/asciidoc/api/subscription/subscribable-companies.adoc
  src/docs/asciidoc/api/subscription/subscription.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/dreamypatisiel/devdevdev/domain/entity/Company.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/entity/Subscription.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/entity/embedded/Url.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/CompanyRepository.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/pick/PickSort.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/pick/custom/PickCommentRepositoryImpl.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/techArticle/BookmarkSort.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/techArticle/SubscriptionRepository.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/techArticle/custom/CompanyRepositoryCustom.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/techArticle/custom/CompanyRepositoryImpl.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/response/SubscriableCompanyResponse.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/TechArticleServiceStrategy.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/subscription/GuestSubscriptionService.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/subscription/MemberSubscriptionService.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/subscription/SubscriptionService.java
  src/main/java/com/dreamypatisiel/devdevdev/web/controller/subscription/SubscriptionController.java
  src/main/java/com/dreamypatisiel/devdevdev/web/dto/SliceCustom.java
  src/main/java/com/dreamypatisiel/devdevdev/web/dto/response/techArticle/CompanyResponse.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/response/TechArticleMainResponseTest.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/GuestSubscriptionServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/GuestTechCommentServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/MemberSubscriptionServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/MemberTechCommentServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/elastic/domain/service/ElasticsearchSupportTest.java
  src/test/java/com/dreamypatisiel/devdevdev/global/utils/AuthenticationMemberUtilsTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/controller/MyPageControllerTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/controller/subscription/SubscriptionControllerTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/controller/techArticle/TechArticleCommentControllerTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/controller/techArticle/TechArticleControllerTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/MyPageControllerDocsTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/SubscriptionControllerDocsTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/TechArticleCommentControllerDocsTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/TechArticleControllerDocsTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/dto/response/techArticle/TechArticleMainResponseTest.java
Labels: documentation, feat

#145 [DP-495] 구독 가능한 기업 상세 조회 API
  src/docs/asciidoc/api/subscription/subscribable-companies.adoc
  src/docs/asciidoc/api/subscription/subscribable-company-detail.adoc
  src/docs/asciidoc/api/subscription/subscription.adoc
  src/main/java/com/dreamypatisiel/devdevdev/domain/entity/Company.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/entity/TechArticle.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/techArticle/SubscriptionRepository.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/techArticle/TechArticleRepository.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/techArticle/custom/CompanyRepositoryCustom.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/techArticle/custom/CompanyRepositoryImpl.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/techArticle/custom/dto/CompanyDetailDto.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/subscription/GuestSubscriptionService.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/subscription/MemberSubscriptionService.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/subscription/SubscriptionService.java
  src/main/java/com/dreamypatisiel/devdevdev/web/controller/subscription/SubscriptionController.java
  src/main/java/com/dreamypatisiel/devdevdev/web/dto/response/subscription/CompanyDetailResponse.java
  src/main/java/com/dreamypatisiel/devdevdev/web/dto/response/subscription/SubscriableCompanyResponse.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/response/TechArticleMainResponseTest.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/GuestSubscriptionServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/GuestTechCommentServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/MemberSubscriptionServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/MemberTechCommentServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/controller/MyPageControllerTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/controller/subscription/SubscriptionControllerTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/controller/techArticle/TechArticleCommentControllerTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/controller/techArticle/TechArticleControllerTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/MyPageControllerDocsTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/SubscriptionControllerDocsTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/TechArticleCommentControllerDocsTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/TechArticleControllerDocsTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/dto/response/techArticle/TechArticleMainResponseTest.java
Labels: documentation, feat

#150 [DP-498] 내가 구독한 기업 목록 API
  src/docs/asciidoc/api/mypage/subscribed-companies.adoc
  src/main/java/com/dreamypatisiel/devdevdev/LocalInitData.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/techArticle/custom/CompanyRepositoryCustom.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/repository/techArticle/custom/CompanyRepositoryImpl.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/member/MemberService.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/subscription/GuestSubscriptionService.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/subscription/MemberSubscriptionService.java
  src/main/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/subscription/SubscriptionService.java
  src/main/java/com/dreamypatisiel/devdevdev/web/controller/member/MypageController.java
  src/main/java/com/dreamypatisiel/devdevdev/web/controller/subscription/SubscriptionController.java
  src/main/java/com/dreamypatisiel/devdevdev/web/dto/response/subscription/SubscribedCompanyResponse.java
  src/main/java/com/dreamypatisiel/devdevdev/web/dto/response/subscription/SubscriptionResponse.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/member/MemberServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/response/TechArticleMainResponseTest.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/response/util/PickResponseUtilsTest.java
  src/test/java/com/dreamypatisiel/devdevdev/domain/service/techArticle/MemberSubscriptionServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/controller/MyPageControllerTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/controller/MyPageControllerUsedMockServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/controller/subscription/SubscriptionControllerTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/MyPageControllerDocsTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/MyPageControllerDocsUsedMockServiceTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/docs/SubscriptionControllerDocsTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/dto/response/techArticle/TechArticleMainResponseTest.java
  src/test/java/com/dreamypatisiel/devdevdev/web/dto/util/PickResponseUtilsTest.java
Labels: documentation, fix, feat

#151 [DP-498] 내가 구독한 기업 목록 API : docs 누락 수정 & default pageSize 6 -> 8 변경
  src/docs/asciidoc/api/mypage/mypage.adoc
  src/docs/asciidoc/api/mypage/subscribed-companies.adoc
  src/main/java/com/dreamypatisiel/devdevdev/web/controller/member/MypageController.java
Labels: documentation, fix
